title = "Custom Interaction Framework"  # From Git
gitRepoUrl = "https://github.com/bluwarerbx/custom-interaction-framework"

gitSourceBranch = "mainmaster"

# From Git
baseUrl = "/D:/Programming/biz/Luau/Custom%20Interaction%20Framework/build/index.html/"