title = "Custom Interaction Framework"  # From Git
gitRepoUrl = "https://github.com/bluwarerbx/custom-interaction-framework"

gitSourceBranch = "mainmaster"

# From Git
baseUrl = "/custom-interaction-framework/"