[package]
name = "biz/custom-interaction-framework"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
promise = "evaera/promise@4.0.0"
net = "sleitnick/net@0.2.0"